Added a feature to the replacer to allow for disabling HTML character escapes
Pinjasaur/templater.js pull request #3
Opened 2024-06-02 21:47 UTC by Bekreth

# About
I've been using this library to build up some simple HTML in combination with HTMX.  Being able to nest HTML elements has proved very helpful, but currently this templater doesn't provide a way to not escape characters.  I've added a new `should_escape` value to the `data` object that is handed in in order to disable escape characters on demand.

2024-06-03 15:21 UTC, Pinjasaur commented
Hey @Bekreth, thanks so much for the contribution. This definitely crossed my mind years ago when I first wrote this.

What are your thoughts on changing the implementation to

1. simply `escape` so it would be e.g. `{ escape: false }`
2. part of the `templater` instance _instead of_ the data object e.g. `const template = templater("template string", { escape: false })`
3. additionally, could enable/disable ad-hoc with something like `template.escape = false`

I'd like to see the first two changes made, I'm not sure if 3. is really necessary.

Let me know if you're able to make these changes and I can give it a proper review. If not, I can probably take a stab at it but I can't promise on the speediness.

2024-06-03 21:50 UTC, Bekreth commented
On your above list:
1. Unfortunately we can't just use `escape` as a keyword since it is a protected word as part of the [Javascript language](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape)
2. I moved the variable as requested.  I'd originally left it in the data object to avoid changing the function interface, but by defaulting it, that should avoid any issues
3. I'm hesitant to embed a togglable value in to a curried function as the behavior is non-obvious.  If a refactor were to be undertaken to convert this to a class, I believe that would make sense though.

2024-06-03 22:51 UTC, Pinjasaur requested changes
Great catch on `escape` being reserved. Didn't even consider that.

I added some notes, mostly I want it to be a configuration object and named something different than snake_case `should_escape`. Let me know your thoughts.

Once we're good here I'll update the docs and manually bump a new release. This repo is so old it used to be on Travis so I'll need to do some manual ops work and see if I can easily migrate it over to GitHub Actions for CI.

2024-06-03 22:51 UTC, Pinjasaur commented on src/templater.js
> +    return function(data, should_escape = true) {
```suggestion
    return function(data, opts) {
```

I'd prefer to see this as an object in case there's other configuration in the future

2024-06-03 22:51 UTC, Pinjasaur commented on src/templater.js
> +          return should_escape ? replacements[tag] || tag : tag;
```suggestion
          return !!opts.autoescape ? replacements[tag] || tag : tag;
```

snake_case doesn't match the rest of the codebase. I looked at Nunjucks for inspiration and they call their configuration key `autoescape`, but I'm open to a different name

2024-06-03 22:51 UTC, Pinjasaur commented on test/basic.spec.js
> +    assert.equal(template(context, false), "<html> tag with 'single' & \"double\" quotes");
```suggestion
    assert.equal(template(context, { autoescape: false }), "<html> tag with 'single' & \"double\" quotes");
```

Again, open to a different name than `autoescape`

2024-06-05 23:51 UTC, Pinjasaur approved these changes
LGTM. Thanks again!

2024-06-05 23:51 UTC, merged